Repository PaulieScanlon/mdx-embed, pull requests merged in 2020-09, with the labels that each got.

#68 Update twitch iframe title and src so that it doesn't include twitchId when empty.
  packages/mdx-embed/src/components/twitch/constructTwitchURL.tsx
  packages/mdx-embed/src/components/twitch/twitch.tsx
  packages/mdx-embed/src/utils/index.ts
Labels: Hacktoberfest

#86 chore/wait-on
  .circleci/config.yml
  CONTRIBUTING.md
  docs/package.json
  package.json
Labels: bug

#87 chore/interface-estlint
  packages/mdx-embed/.eslintrc.js
  packages/mdx-embed/src/components/general-observer/general-observer.tsx
Labels: Hacktoberfest, help wanted
